name: Publish

on:
  schedule:
    - cron:  '0 2 */3 * *'

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install
        working-directory: engine
        run: npm i
      - name: Create google-keys
        working-directory: engine
        run: echo ${{secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON}} > google-keys.json
      - name: check google-keys
        working-directory: engine
        run: cat ${{secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON}}
      - name: Gulp default
        working-directory: engine
        run: gulp
        